import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '../../Redux/Provider'
import { ApiProvider } from '@reduxjs/toolkit/query/react'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
    
      <body className={inter.className}>{children}</body>

      </Providers>

    </html>
  )
}
